# pycares errno values (not DNS RCODEs — see pycares.errno)
NO_DATA = 1   # ARES_ENODATA
SERVFAIL = 3  # ARES_ESERVFAIL
NXDOMAIN = 4  # ARES_ENOTFOUND
REFUSED = 6   # ARES_EREFUSED
TIMEOUT = 12  # ARES_ETIMEOUT
